### ISSUE TITLE
Can't save Form Builder

### ISSUE THREAD

**Issue by kimisgold** [chnm/Datascribe-module#1]
I get the following error when I try to save the form. I've tried uninstalling and re-installing the module.

```
Doctrine\DBAL\DBALException
Unknown column type "json" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

Details:

Doctrine\DBAL\DBALException: Unknown column type "json" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information. in /Users/kim/Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:240
Stack trace:
#0 /Users/kim/Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php(172): Doctrine\DBAL\DBALException::unknownColumnType('json')
#1 /Users/kim/Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(111): Doctrine\DBAL\Types\Type::getType('json')
#2 /Users/kim/Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(277): Doctrine\DBAL\Statement->bindValue(6, Array, 'json')
#3 /Users/kim/Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1014): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /Users/kim/Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /Users/kim/Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /Users/kim/Sites/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(369): Doctrine\ORM\EntityManager->flush()
#7 /Users/kim/Sites/omeka-s/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
#8 /Users/kim/Sites/omeka-s/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#9 /Users/kim/Sites/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(152): Omeka\Api\Manager->update('datascribe_data...', '1', Array, Array, Array)
#10 /Users/kim/Sites/omeka-s/modules/Datascribe/src/Controller/Admin/DatasetController.php(66): Omeka\Mvc\Controller\Plugin\Api->update('datascribe_data...', '1', Array)
#11 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Datascribe\Controller\Admin\DatasetController->editAction()
#12 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#15 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#16 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#19 /Users/kim/Sites/omeka-s/index.php(21): Zend\Mvc\Application->run()
#20 {main}
```

**Comment by jimsafley** [comment]
Doctrine recently replaced the "json_array" data type with the "json" data type. Running `gulp deps:update` on the command line will fix this issue by upgrading Doctrine to a version that includes the "json" data type.
