### ISSUE TITLE
Non-dataset user transcriber still sees save button

### ISSUE THREAD

**Issue by mebrett** [chnm/Datascribe-module#59]
Logged in as a Global Editor level user. Went browsing through DataScribe projects which were visible but on which I am not a user.
When looking at items, I still get the "Save" button:
![Screen Shot 2020-07-15 at 9 59 37 AM](https://user-images.githubusercontent.com/2314070/87556385-93732100-c684-11ea-8234-ee175e80ab9e.png)

I can't lock the record to myself, as would be usual for a transcriber or non-GlocalAdmin. But I can click the save button. When I do, I get the following error:

```
Omeka\Api\Exception\PermissionDeniedException: Permission denied for the current user to update the Datascribe\Entity\DatascribeItem resource. in /websites/datascribet/www/application/src/Api/Adapter/AbstractEntityAdapter.php:584
Stack trace:
#0 /websites/datascribet/www/application/src/Api/Adapter/AbstractEntityAdapter.php(529): Omeka\Api\Adapter\AbstractEntityAdapter->authorize(Object(Datascribe\Entity\DatascribeItem), 'update')
#1 /websites/datascribet/www/application/src/Api/Adapter/AbstractEntityAdapter.php(367): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Datascribe\Entity\DatascribeItem), Object(Omeka\Stdlib\ErrorStore))
#2 /websites/datascribet/www/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
#3 /websites/datascribet/www/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#4 /websites/datascribet/www/application/src/Mvc/Controller/Plugin/Api.php(152): Omeka\Api\Manager->update('datascribe_item...', 112, Array, Array, Array)
#5 /websites/datascribet/www/modules/Datascribe/src/Controller/Admin/RecordController.php(48): Omeka\Mvc\Controller\Plugin\Api->update('datascribe_item...', 112, Array)
#6 /websites/datascribet/www/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Datascribe\Controller\Admin\RecordController->browseAction()
#7 /websites/datascribet/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /websites/datascribet/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /websites/datascribet/www/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#10 /websites/datascribet/www/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 /websites/datascribet/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /websites/datascribet/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /websites/datascribet/www/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#14 /websites/datascribet/www/index.php(21): Zend\Mvc\Application->run()
#15 {main}
```

Seems to me that the save button should not be visible to non-Admin users who aren't on the project?

**Comment by jimsafley** [comment]
Fixed in 5e2f65e03242aa23978682ac1bcab8584ada0341
